### PR TITLE
libsecp256k1: Replace OpenSSL ECDSA with libsecp256k1

### PR DESCRIPTION
**Pull request by aido**
Hi,

Pull request to start migration from OpenSSL ECDSA to libsecp256k1.

Git submodule the correct approach?
Maybe a new branch in jgarzik/picocoin specially for work on this?

### CODE REVIEW

**Comment by dtebbs** [comment]
@aido Seems like a valid approach if we can make it work.
On a related note, I have the code ready that replaces all the main key operations with the secp256k1 lib, based on your branch.

  https://github.com/dtebbs/picocoin/tree/secp256k1_keys

Locally everything builds and tests pass, but for whatever reason, travis completely fails on linux with link errors I can't reproduce on my machine.

  https://travis-ci.org/dtebbs/picocoin

@aido you no doubt know much more about automake etc than I do.  If you get a chance to take a look at what I'm doing wrong that would be a huge help.  Otherwise I'll keep plugging away.

**Comment by aido** [comment]
Hi @dtebbs,

I just had a quick look but I think libsecp256k1 may need the ecdh and schnorr modules enabled in travis.

Something like this _may_ work:
```
  global:
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - BUILD=check
    - ENABLE_COVERAGE=no
    - ENABLE_VALGRIND=no
    - ENABLE_ECDH=yes
    - ENABLE_SCHNORR=yes
.
.
.
script:
  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
  - PICOCOIN_CONFIG_ALL="--prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
  - ./configure --cache-file=config.cache --enable-coverage=$ENABLE_COVERAGE --enable-valgrind=$ENABLE_VALGRIND --enable-module-ecdh=$ENABLE_ECDH --enable-module-schnorr=$ENABLE_SCHNORR $PICOCOIN_CONFIG_ALL $PICOCOIN_CONFIG || ( cat config.log && false)
  - make -s $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL ; false )
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
  - make $MAKEJOBS $BUILD
```

**Comment by dtebbs** [comment]
Thanks @aido.  I think you are right about the randomization.  Should be fixed in my branch now, for when the build config changes are ready.

**Comment by aido** [comment]
Hi,

Pull request updated with suggestions from @dtebbs so that all Travis builds now complete successfully.

A connection glitch on one of the Travis builds for this pull request has caused it to fail:
```
Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libssl-dev amd64 1.0.1-4ubuntu5.35
  Could not connect to us.archive.ubuntu.com:80 (91.189.91.23), connection timed out [IP: 91.189.91.23 80]
```
The exact same commits successfully build in my branch (https://travis-ci.org/aido/picocoin/builds/123332920)

I suggest clicking the 'Restart Build' button in Travis to try build again.

**Comment by dtebbs** [comment]
@aido Thanks for merging in my commit.

@jgarzik If you are satisfied with the code, I think this could represent a sensible point at which to merge.

In summary:  the key API has not changed (except to expose a function to clean up the secp256k1_context), but EC operations are now performed with the secp256k1 library.  Later PR's can replace the remaining OpenSSL usage for (hashing, random number gen, ...) and update the bp_key API to give the caller control over allocations and the secp256k1_context lifetime.

**Comment by jacobbogers** [comment]
Why is this happening?  performance reasons? what is gained by this?

**Comment by aido** [comment]
https://bitcoin.stackexchange.com/questions/36136/is-libsecp256k1-faster-than-openssl

**Comment by jacobbogers** [comment]
Thanks for the link, on the link there is quote (...This talks about signature verification, which is currently the bottleneck when catching up to the blockchain...)
Ok, so my followup question is:
but Picocoin (as I understand it) doesnt save the blockchain, .., so is this functionality needed here?
How does Picocoin handle the blockchain and would it benefit from libsecp256k1?

**Comment by aido** [comment]
Hi @jacobbogers,

This doesn't really answer your question directly but from the owner of picocoin has said:

> we are moving in the direction of removing openssl completely, and instead using libsecp256k1

https://github.com/jgarzik/picocoin/pull/44#issuecomment-201278746

and

> Further, the trend for upstream bitcoind, and it seems logical to follow that here, is integrating just the crypto algorithms that are needed, directly into the source code: sha256, ripemd160, etc. The exception then being ECDSA, which is obtained from sipa's libsecp256k1

https://github.com/jgarzik/picocoin/pull/25#issuecomment-4427463

**Comment by jacobbogers** [comment]
Thanks for clarifying the motivation behind this move..

**Comment by jgarzik** [comment]
concept ACK - will do some testing and verification myself over the next week.

**Comment by aido** [comment]
Hi @jgarzik,

One of the reasons for and advantage of making libsecp256k1 a submodule is that the latest and greatest version (if any version at all) may not be available for every OS/distro so may have to be downloaded, built and installed separately before building picocoin. As a submodule the user does not need to perform these additional steps and the same steps as always are followed for building picocoin. Also, any changes or security updates to libseck256k1 may easily be added to picocoin with a single `git pull` from the libsecp256k1 directory. This is no more a maintenance burden  than updating a `PKG_CHECK_MODULES` version in `configure.ac`.

A blatant attempt at trying to sway your decision :-)

**Comment by dtebbs** [comment]
Regarding submoduling, one thing that is quite annoying is that `make check` in the top dir now takes an order of magnitude longer because it runs all the checks for the submodule.  It would be nice if there were a way to only run our own tests by default, (with the option to also run the secp256k1 ones, even if that meant running `make check` from the secp256k1 dir).

I tried the obvious change in the Makefile, but quickly hit the issue that make conditionals can't go into `Makefile.am` (I'm a complete noob with automake).  Anyone know a nice way to prevent the `check` target from traversing into secp256k1?

**Comment by aido** [comment]
Hi @dtebbs,

Have you tried:
```./autogen.sh
./configure --enable-tests=no
make check
```

It only disables the libsecp256k1 checks, not libccoin ones.

**Comment by dtebbs** [comment]
Thanks @aido.  That does work.
I've made a few more changes in my branch (now called `secp256k1` to match yours)
https://github.com/dtebbs/picocoin/tree/secp256k1

- Disabled secp256k1 tests by default (added `--enable-secp256k1-tests` flag)
- Fix for key gen (retry if random secret is invalid)
- Rebased on to recent changes in master

Up to you whether you want to reset your branch on to mine and update the PR that way, or I can create a new PR.

**Comment by aido** [comment]
Merged latest master branch of jgarzik/picocoin so there are no conflicts.

**Pull request merged**
