### PR TITLE
Make picocoin wallet handling code more generic, push into libccoin

### PR DESCRIPTION
**Pull request by joshcartwright**
Yes, yes, I should have probably have been writing tests for my other pending PR...

However, testing the wallet handling code will be a bit simpler if there was better isolation between a "wallet core" and a "picocoin wallet" (where the picocoin wallet has the notion of a "current" wallet and "current" block chain).

This is the work to do just that.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
@joshcartwright really nice to see that you are working on this! Thanks.
Have plans to review and test during this week.

**Comment by jgarzik** [comment]
LGTM

**Comment by jgarzik** [comment]
Pushed the first several of these to the repo.  Will wait for feedback/test/resync before proceeding further.

**Comment by joshcartwright** [comment]
Resynced, folded in the constify patch from #38, and added some basic tests.

**Comment by jgarzik** [comment]
Merged.  Had to clean up some compiler warnings and minor bugs.

**Comment by joshcartwright** [comment]
Thanks, and sorry for the minor fixups, I'll change my workflow to be more aggressive about compiler warnings.

Also, I'll take a look at why the wallet serialization test is failing.

**Pull request merged**
