### PR TITLE
adding debian folder

### PR DESCRIPTION
**Pull request by favioflamingo**
Hello, I added a debian folder so that someone could run the following 3 commands to compile a deb package:
1. `dh_make -p picocoin_0.1  --createorig -l`
2. `debuild -S`
3. `debuild -b`

I hope this can make the library more convenient for people to use.  

An additional point/question.  I tried adding a version info line to lib/Makefile.am along the lines of `libccoin_la_LDFLAGS = -module -shared  -version-info 0:1:1` .  I read that some libraries rely on just the package name to indicate compatibility as opposed to using the version-info line.  In the former case, the dynamic shared library is installed as libccoin.so.0.0.0.  So, I was a little confused as to what to do on this point.

### CODE REVIEW

**Comment by aido** [comment]
Hi @favioflamingo,

Not sure if you spotted this but all the Travis builds fail: 

```
libtool: link: `0:1:1' is not valid version information
```

**Comment by favioflamingo** [comment]
Hello,
I have to remove a line I added to the Makefile.am file setting a version
info for the libccion library.  I'll try to do it this weekend.

**Comment by jgarzik** [comment]
ACK - however, includes some non-debian code changes which should not be in this pull request.

**Comment by favioflamingo** [comment]
As a slightly related question, would it be possible at some point to add prefixes to the opcodetype in ccoin/script.h ?  For example, instead of OP_N, ccoin_OP_N?  The reason why I ask is because I cannot use picocoin with Perl since the operator names from script.h conflict with those in Perl.  I have done that in https://github.com/favioflamingo/picocoin/blob/ef-master/include/ccoin/script.h

**Comment by jgarzik** [comment]
Looks good, thanks!

**Pull request merged**
