### PR TITLE
Replaced OpenSSL for hash functions and AES

### PR DESCRIPTION
**Pull request by dtebbs**
This change pulls SHA1, SHA256, SHA512, RIPEMD160 and AES code into the library, into a crypto subdir.

SHA1 is a conversion to C of the C++ code in bitcoin core.  Tests for standard test vectors have been added.

AES has been moved into the ccoin lib, along with wrappers exposing similar behavior to the OpenSSL calls.  Tests for this have been added, with test data generated by the old OpenSSL code to ensure that behavior has not changed.

This change will almost certainly conflict with the secp256k1 PR, so naturally I'll rebase whichever one, depending on which gets merged first.  I wanted to put this up anyway so it can be reviewed and discussed.

### CODE REVIEW

**Comment by aido** [comment]
Hi @dtebbs,

I see that as well as [libsecp256k1 ](https://github.com/bitcoin-core/secp256k1) @sipa has written his own implementation of several crypto functions: 

https://github.com/sipa/Coin25519/tree/master/src/crypto

Although they do not seem to have had many updates recently.

There is also the [CT-AES module](https://github.com/bitcoin-core/ctaes) available in the bitcoin-core Github repository that can easily be added as a submodule or whatever.

I'm not sure if there is any advantage to using these over the ones you have chosen but they are written by bitcoin core developers and all use a MIT license.

**Comment by sipa** [comment]
The code is Coin25519 was a very short lived experiment, ages ago. Please don't use it for anything.

Bitcoin Core has its own naive implementations of cryptographic functions in https//github.com/bitcoin/bitcoin/tree/master/src/crypto. Those are well reviewed and well tested. It also includes ctaes as a subtree.

**Comment by libbitc** [comment]
Hi Duncan,

Just a suggestion but should AES code be placed in the libccoin library?

https://github.com/dtebbs/picocoin/blob/sha_ripemd160_aes/lib/Makefile.am#L8-L14

AES is used by the wallet which should probably not be part of the core library. Here's how I did it in my fork of picocoin:

https://github.com/libbitc/libbitc/blob/master/lib/Makefile.am#L60-L66

I create a convenience library for AES. The plan is to eventually create a separate wallet library containing the AES code.

**Comment by jonasschnelli** [comment]
You guys might also want to have a look at https://github.com/libbtc/libbtc

**Comment by dtebbs** [comment]
@libbitc Yeah, that makes sense.  Actually, I was thinking of crypto as a kind of utility module or lib, but I see the point that aes could be split out.

**Comment by dtebbs** [comment]
@jonasschnelli yes, libbtc looks good and seems to be taking a similar direction to libccoin.  (and great name, btw :)

I'm interested in developing the client framework functionality in picocoin (which I think you've dropped from libbtc).  In any case there should be value in combining efforts if possible.

**Comment by jonasschnelli** [comment]
@dtebbs: I'm also interested in the client features. Check out the wallet format (liblogdb) and there are some client/wallet branches (https://github.com/jonasschnelli/libbtc/commit/742c886dfbb685bd6aa1241be7a6d56918445679).

I'd like to see a full featured SPV client built into libbtc with an optional compile flag in future.

**Comment by libbitc** [comment]
I had similar objectives in mind when I forked picocoin into libbitc.

There is a lot of similarities between libbtc and picocoin but I chose to fork picocoin because it has the network functionality ready to go and also has some clients already written.

My short term goal with libbitc is to get it to pass most of the more recent bitcoin core tests and then passing those updates back into picocoin. When Jeff created picocoin a few years ago he used the then available tests from bitcoin core. I don't think they have been updated in picocoin much since then.

My mid-term goal with libbitc is to expand the wallet to use Jonas'  liblogdb.
 
Longer term I plan to add LMDB for the block database.

I agree with Duncan, there is always value in combining efforts if possible.

**Comment by jgarzik** [comment]
Needs rebase.

**Comment by dtebbs** [comment]
I've rebased the changes on to latest master

**Comment by jgarzik** [comment]
Closing; merged similar pull from @aido

**Pull request closed without merging**
