### PR TITLE
Replace OpenSSL crypto functions

### PR DESCRIPTION
**Pull request by aido**
Hi,

This pull request is almost exactly the same as @dtebbs pull request #77.

The main difference is that this PR uses sipa's simple constant-time AES implementation: https://github.com/bitcoin-core/ctaes

This is the first draft. If it agreed that this is the way to go I will tidy up and add some tests.

Also, the AES code currently builds it's own separate noinst library libccoinaes.la. This is in preparation for a possible future pull request that will modularize the wallet code, placing wallet code and AES code in their own library. This modularization is in line with the direction bitcoin-core is also going.

If merging dtebbs PR #77 then this PR may be closed orr vice versa

### CODE REVIEW

**Comment by jgarzik** [comment]
LGTM, ACK

Whichever pull req builds and tests successfully first is fine with me :)

**Comment by aido** [comment]
Hi,

Some strange stuff happening on Travis with this pull request.
Most builds complete successfully except 3 of the 4 builds where coverage is enabled.

There is currently a Travis broadcast about build failures due to new sudo-enabled Precise and Trusty images but I don;t think this is related.

**Comment by aido** [comment]
Hi,

All tests pass when using `./configure --enable-coverage=yes` or `./configure 'CC=clang'` on Linux but 1 test fails when using `./configure --enable-coverage=yes 'CC=clang'`.

Currently trying to figure out why.

**Comment by jgarzik** [comment]
Merged, thanks to both @aido and @dtebbs

**Pull request merged**
