### PR TITLE
Provide mechanism to get oldest key

### PR DESCRIPTION
**Pull request by joshcartwright**
This work is largely based on the work of @jonasschnelli , modified to use 64-bit time-since-epoch, and perform serialization slightly differently.

Also, with this PR is the addition of a couple macros for conveniently iterating over the keys in a keychain.

All of this work is furthering the goal of providing full SPV functionality.

### CODE REVIEW

**Comment by joshcartwright** [comment]
Still needs some work; it doesn't properly handle the key-less wallet case well, and I'd like to make it function generically over _any_ wallet and not just the current one.

**Comment by joshcartwright** [comment]
Fixed up.  Should be ready to pull now.  Note that I further broke down the commits into ones which touch libccoin and one which touches the picocoin wallet.  I do feel that most of the wallet logic should exist in libccoin, but that can wait for another day.

**Comment by jgarzik** [comment]
Comments:
* ACK first commit - merged
* If time & motivation are available, creating some simple wallet unit tests would be very helpful
* I am wondering if bp_key is the best place for creation time.  it was intended to be more fundamental.  A wallet-key structure wrapping a more basic ecdsa key seems better.

**Comment by joshcartwright** [comment]
Cool.  Actually, I had the same thought as you yesterday.  We certainly need tests, I'll take a stab at that.

Do you not consider the "wallet" to be fundamental?

**Comment by jgarzik** [comment]
It is a matter of layering.  There are several existing bp_key uses which do not use this time feature, as the data structure was intended similar to CKey in bitcoin C++, which simply wraps and abstracts an ecdsa keypair (where the private component is optional).

A "birthday" is metadata attached to a key by a wallet.  If the wallet has other metadata - now or in the future - for keys, it makes sense to have a bp_walletkey structure.  If this time field will be the only piece of metadata attached to a key for the forseeable future, adding it to bp_key is less desireable but OK.

**Comment by jonasschnelli** [comment]
I agree with @jgarzik `bp_key` is the EC layer/wrapper. There should be a struct, ser/deser handling of something like a `bp_walletkey`. Or even better, let's do it like bitcoin-core: keep the `"privkey"` record. Add another `"keymeta"` record type with metadata for the key (introduce somethink like `bm_metadata`). This would require having something like a Key-ID, this could the pub keys hash (to link between bp_key and bm_metadata.

**Comment by jgarzik** [comment]
@jonasschnelli FWIW, the key/metadata separation was purely an implementation convenience.  It is annoying to have to match up the two records; however keys in Bitcoin Core wallet began their life without metadata, dictating separate treatment.

**Comment by joshcartwright** [comment]
Here's an attempt at adding a "wallet_key" object whose attempted purpose is to be a container of both a bp_key and metadata (starting with the birthday, but other metadata may be useful in the future).  Still working on tests...

**Comment by jgarzik** [comment]
@joshcartwright LGTM

**Comment by joshcartwright** [comment]
This PR needs some love.  I'll get it rebased on #39 if that's decided to be a good direction to go.

**Comment by joshcartwright** [comment]
Rebased on #39 .  Let me know if it just makes sense to make these a single PR.  Oh, and tests.

**Comment by jgarzik** [comment]
Looks like a good direction

**Comment by joshcartwright** [comment]
Updated to address @jgarzik feedback.

**Comment by jgarzik** [comment]
ACK - rebase this to fix conflicts and trigger a Travis-CI test - and we can get this merged

**Comment by jgarzik** [comment]
Closing -- hoping somebody will come back, rebase and refresh it for merging.

**Pull request closed without merging**
