### PR TITLE
osx and automake improvements

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by jgarzik** [comment]
mostly ok. issues:

* General dislike for optional binary building.  That leads to progressive breakage as people turn things off for expedience, then leave them off.  Preference is for developers to reach the minimum hurdle of building programs that require some comment cli dependencies like jansson or libevent.  If the dep list gets too onerous (Qt!), can revisit.

* requiring argp breaks linux.

**Comment by jonasschnelli** [comment]
This should no compile on linux as well as on osx. I also removed the enable-brd option because i agree with @jgarzik concerns.

**Comment by joshcartwright** [comment]
As mentioned in #bitcoin-dev, a glib-2.0 check just doesn't make sense for argp_parse(), as argp_parse() is provided by _glibc_...

**Comment by jgarzik** [comment]
manually merged most of this

I think you confused "glib" and "glibc" here, so snipped that part.

**Comment by jonasschnelli** [comment]
Thanks for the manual merge! Yes I was confused and I have a lack of know how regarding the gnu stack.

**Pull request closed without merging**
