### PR TITLE
Replace OpenSSL BigNum with GMP

### PR DESCRIPTION
**Pull request by aido**
Hi,

In this pull request nearly all instances of OpenSSL BigNum have been replaced with GMP mpz_t. The remaining instances of OpenSSL BigNum relate to OpenSSL ECDSA.

This is in preparation of the next step, replacing OpenSSL ECDSA with Sipa's libsecp256k1.

The ultimate goal being to integrate just the crypto algorithms that are needed, directly into the source code: sha256, ripemd160, etc.

Good idea or bad?

### CODE REVIEW

**Comment by dtebbs** [comment]
Would be great to replace OpenSSL and reduce all those allocations.

**Comment by aido** [comment]
Hi dtebbs,

Feel free to assist:

https://github.com/aido/picocoin/tree/secp256k1

**Comment by jgarzik** [comment]
Yes, good direction @aido 

Minor nits only...

**Comment by jgarzik** [comment]
Comments:
* cstr_prepend_buf() needs basic tests
* adding stdio.h include seems odd -- what triggered that?  Usually you want to add the include at the root cause.

Did you test this locally, setting TEST_MAINNET_VERF=[bootstrap.dat] ?

**Comment by aido** [comment]
Hi,

`cstr_prepend_buf()` basic tests now added.

Adding `stdio.h` include does indeed seems odd but I think this was needed because `<openssl/bn.h>` was removed from `buint.h`.

 `stdio.h` was added to two files, `test/message.c` and `src/peerman.c`.

Compiling `test/message.c` with gcc -H shows the following dependency tree:
```
. ../include/ccoin/message.h
.. ../include/ccoin/core.h
... ../include/ccoin/buint.h
.... /usr/include/openssl/bn.h
..... /usr/include/stdio.h
```
And compiling `src/peerman.c` with gcc -H shows the following dependency tree:
```
. peerman.h
.. ../include/ccoin/core.h
... ../include/ccoin/buint.h
.... /usr/include/openssl/bn.h
..... /usr/include/stdio.h
```

I tested this locally, setting TEST_MAINNET_VERF=[bootstrap.dat] but I used a small bootstrap.dat file. I will test with a much larger bootstrap.dat file when I get a chance.

**Pull request merged**
