### PR TITLE
Tidy up network code

### PR DESCRIPTION
**Pull request by aido**
Hi,

This pull request attempts to tidy up the network code by placing all network functionality into it's own separate library (`noinst_LTLIBRARIES = libccoinnet.la`).

Also, all the duplicated network code in `src/brd.c` and `src/net.c` has been combined into a single file in `lib/net/net.c`.

These changes will almost certainly conflict with the other open pull requests, so naturally I'll rebase whichever one, depending on which gets merged first. I wanted to put this up anyway so it can be reviewed and discussed.

### CODE REVIEW

**Comment by dtebbs** [comment]
@aido this looks like a good direction.  I have also been doing a bit of work on modularizing, to make it easier to create various clients.

  https://github.com/dtebbs/picocoin/tree/net_client

My branch is still a mess and I haven't had a chance to work on it for a while, but just letting you know in case there is stuff to share.  I'll trying merging your branch to mine in when I get time.

**Comment by aido** [comment]
Hi @dtebbs,

The current pull request mostly updates the network code used by `brd`. I have another commit nearly ready that will update the network code related to the`picocoin` client i.e. moves `src/net.c` into `lib/net/net.c`. I nearly have it working but am debating with myself if the way I'm doing it is the best approach.

Network code should more or less be fully modularized then. I am trying to keep as much non-network code (blkdb lookup etc.) out of `lib/net/net.c`.

Regards,
Aido

**Comment by aido** [comment]
Hi,

Pull request ready for constructive criticism now.

At the moment there may be an issue around `event_base_dispatch` in the `network_child` function in `src/main.c`:

https://github.com/aido/picocoin/blob/051a9ea9e67a9114b3108579d1d2bdf68f0aad5a/src/main.c#L388-L397

but I am looking into it.

**Comment by aido** [comment]
Hi @dtebbs,

I was looking at your fork and some of the work to modularize, making it easier to create various clients. Good ideas.

Maybe if this pull request was merged after review all net code would be in one place and it would then be easier to implement some of your work on top of that with another pull request,

**Comment by dtebbs** [comment]
Hi @aido,
Yes.  I think this separate lib and the factorization is a good basis for more modularization.
Having a quick check through the diff, the only nit I'd pick would be the inconsistent indentation in a few places.  The direction seems good to me.

**Comment by aido** [comment]
Hi @dtebbs,

I changed editor for some edits and didn't spot the different indentation until after I pushed to github. I think I've caught them all now in the latest commit.

Any sign of @jgarzik around here lately? :-) Pull requests piling up.

**Comment by jgarzik** [comment]
Merging this one first...

**Pull request merged**
